config/routes.rb
BooksubzApp::Application.routes.draw do
  resources :categories

  devise_for :users

  resources :users, :only => [:show, :index, :destroy, :update]

  resources :books

  resources :comments

  resources :orders

  root to: "index#index"

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name, :image

  has_and_belongs_to_many :books

  mount_uploader :image, CategoryImageUploader

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<section class="category_index_page">
  <div class= "row show-grid">
    <div class="row">
        <% @categories.each do |category| %>
        <div class="col-xs-6 col-sm-4 col-md-3">
          <%= link_to category do %>
          <div class="thumbnail">
            <%= image_tag category.image, class: 'category_image' %>
            <div class="caption">
              <h5 class="category_thumbnail_caption"><%= category.name %></h5>
            </div>
          </div>
          <% end %>
        </div>
        <% end %>
    </div>
  </div>
</section>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<div class="row">
  <% @category.books.each do |book| %>
  <div class="col-xs-6 col-sm-4 col-md-3">
    <%= link_to book do %>
    <div class="thumbnail">
      <%= image_tag book.cover_picture, class: 'book_image' %>
      <div class="caption">
        <div class="category_thumbnail_caption">
          <h5><%= book.name %></h5>
          <h5><%= book.user.name %></h5>
          <h5>£<%= book.price %></h5>
          <div ng-controller="RatingDemoCtrl">
            <rating ng-model="rate" max="max" readonly="isReadonly" on-hover="hoveringOver(value)" on-leave="overStar = null"></rating>
            <span class="label" ng-class="{'label-warning': percent<30, 'label-info': percent>=30 && percent<70, 'label-success': percent>=70}" ng-show="overStar && !isReadonly">{{percent}}%</span>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
  <% end %>
</div>

 



<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back to all Categories', categories_path %> | 
<%= link_to 'Destroy', category_path, method: :delete, data: { confirm: 'Are you sure?' } %>