config/routes.rb
BooksubzApp::Application.routes.draw do
  resources :categories

  devise_for :users

  resources :users, :only => [:show, :index, :destroy, :update]

  resources :books

  resources :comments

  resources :orders

  root to: "index#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="booksubzApp">
<head>
  <title>BooksubzApp</title>
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-rc.1/angular.min.js"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- BOOTSTRAP Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <!-- BOOTSTRAP Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
  <!-- BOOTSTRAP Latest compiled and minified JavaScript -->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js" ></script>

</head>
<body ng-controller="BasketController">
  <div class="page_wrap">
    <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">booksubz</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <li class="search_input"><%= search_form_for @q, :html => {:class => "navbar-form navbar-left"} do |f| %>
              <%= f.text_field :name_or_user_name_cont, placeholder: "book, author" %></li>
              <li class="search_submit"><%= f.submit %>
              <% end %></li>
          <ul class="nav navbar-nav navbar-right">
            <li class="active"><%= link_to "Account", current_user %></li>
            <li class="active"><a href="#">
              <span class="glyphicon glyphicon-shopping-cart">{{ basket }}</span>
            </a></li>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
<!--               <li class="active"><%= current_user.email %></li>
 -->              <li class="active"><%= link_to "Edit profile", edit_user_registration_path %></li>
              <li class="active"><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li class="active"><%= link_to "Sign up", new_user_registration_path %></li>
              <li class="active"><%= link_to "Login", new_user_session_path %></li>
            <% end %>
          </ul>
        
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
        <ul class="nav navbar-nav nav_3" >
          <li class="dropdown nav_2">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Categories <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "All", categories_path %></li>
              <li class="divider"></li>
              <li>
                <% @categories.each do |category| %>
                  <%= link_to category.name, category %>
                <% end %>
              </li>
            </ul>
          </li>
          <li class="active nav_2"><%= link_to "Bestsellers", books_path %>
          <li class="active nav_2"><%= link_to "Free e books", books_path %>
          <li class="active nav_2"><%= link_to "Authors", users_path %></li>
        </ul>


      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <!--   <div>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      
    </div> -->


  <%= yield %>

  </div>

  <footer class="site_footer">
    <li>|</li>
    <li><%= link_to "about", page_path('about') %></li>
    <li>|</li>
    <li><%= link_to "terms & conditions", page_path('terms') %></li>
    <li>|</li>
    <li>© Piers Karpinski 2014</li>
    <li>|</li>
  </footer>

</body>
</html>